### ISSUE TITLE
iCloud host error [MY_APPLE_ID]

### ISSUE THREAD

**Issue by saqibomer** [bstrebel/fmip#1]
I am getting error 

> iCloud host error [MY_APPLE_ID]
GET / - - ms - -

**Comment by bstrebel** [comment]
Please double check your apple id and password and post the output of the following command:

` curl --request POST --header "Authorization: Basic AUTH" "https://fmipmobile.icloud.com/fmipservice/device/YOUR_APPLE_ID/initClient" --dump-header -`

where AUTH is the [base64 encoded](https://www.base64encode.org/) authorization string in the format "YOUR_APPLE_ID:YOUR_PASSWORD"
